import type { CSSProperties } from "react";

export const s = {
  root: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  head: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  titleRow: { display: "flex", alignItems: "baseline", gap: 10 } satisfies CSSProperties,
  title: { margin: 0, fontSize: 16, fontWeight: 650 } satisfies CSSProperties,
  count: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  hint: { margin: 0, fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.45 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  version: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  actions: { display: "flex", gap: 8 } satisfies CSSProperties,
  diffBody: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 0, minHeight: 240 } satisfies CSSProperties,
  pane: { display: "flex", flexDirection: "column", minWidth: 0, borderRight: "1px solid var(--border)" } satisfies CSSProperties,
  paneLast: { display: "flex", flexDirection: "column", minWidth: 0 } satisfies CSSProperties,
  paneLabel: {
    padding: "8px 14px",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  paneBody: {
    margin: 0,
    padding: 14,
    fontSize: 12,
    lineHeight: 1.45,
    whiteSpace: "pre-wrap",
    overflow: "auto",
    maxHeight: 420,
  } satisfies CSSProperties,
  diffFooter: { display: "flex", justifyContent: "flex-end" } satisfies CSSProperties,
} as const;
