import type { CSSProperties } from "react";

export const s = {
  panel: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    minWidth: 0,
  } satisfies CSSProperties,
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  path: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  toggle: { display: "inline-flex", gap: 4 } satisfies CSSProperties,
  toggleBtn: {
    padding: "4px 10px",
    fontSize: 12,
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
    font: "inherit",
  } satisfies CSSProperties,
  toggleBtnOn: {
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    border: "1px solid var(--border-strong)",
  } satisfies CSSProperties,
  editor: { padding: "12px 14px", display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  banner: {
    fontSize: 12,
    padding: "6px 10px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  labelRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  badge: {
    fontSize: 11,
    padding: "1px 6px",
    borderRadius: 999,
    border: "1px solid var(--border-strong)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  textarea: {
    width: "100%",
    minHeight: 320,
    boxSizing: "border-box",
    padding: 10,
    fontSize: 13,
    lineHeight: 1.6,
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-base, transparent)",
    color: "var(--text-primary)",
    resize: "vertical",
  } satisfies CSSProperties,
  actions: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  error: { fontSize: 12, color: "var(--danger, #d33)" } satisfies CSSProperties,
  usedBy: {
    padding: "6px 14px",
    fontSize: 12,
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  content: {
    padding: "18px 24px",
    fontSize: 14,
    lineHeight: 1.7,
    color: "var(--text-secondary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
} as const;
