import type { CSSProperties } from "react";
import { EDITOR_HEIGHT, EDITOR_LINE_HEIGHT } from "./constants";

const field = {
  width: "100%",
  padding: "10px 12px",
  borderRadius: 7,
  border: "1px solid var(--border-strong)",
  background: "var(--bg-elevated)",
  color: "var(--text-primary)",
  fontSize: 14,
  outline: "none",
  boxSizing: "border-box",
} satisfies CSSProperties;

export const s = {
  body: { padding: "8px 4px 0", display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  banner: {
    padding: "10px 12px",
    borderRadius: 8,
    background: "color-mix(in srgb, var(--accent) 12%, transparent)",
    color: "var(--text-secondary)",
    fontSize: 13,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  field: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  label: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.4 } satisfies CSSProperties,
  row: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, alignItems: "start" } satisfies CSSProperties,
  enabled: { display: "flex", alignItems: "center", gap: 10, marginTop: 28 } satisfies CSSProperties,
  input: { ...field } satisfies CSSProperties,
  textarea: { ...field, resize: "vertical", lineHeight: 1.5 } satisfies CSSProperties,
  select: { ...field, appearance: "none", cursor: "pointer" } satisfies CSSProperties,
  selectWrap: { position: "relative" } satisfies CSSProperties,
  selectIcon: { position: "absolute", right: 12, top: 13, color: "var(--text-muted)", pointerEvents: "none" } satisfies CSSProperties,
  editor: { border: "1px solid var(--border-strong)", borderRadius: 7, background: "var(--code-bg)", overflow: "hidden" } satisfies CSSProperties,
  fileBar: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 14px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  fileIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  fileName: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  tokens: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  code: { display: "flex", height: EDITOR_HEIGHT } satisfies CSSProperties,
  gutter: {
    width: 44,
    flexShrink: 0,
    overflow: "hidden",
    padding: "12px 10px 12px 0",
    textAlign: "right",
    fontSize: 13,
    lineHeight: `${EDITOR_LINE_HEIGHT}px`,
    color: "var(--text-muted)",
    userSelect: "none",
    borderRight: "1px solid var(--border)",
  } satisfies CSSProperties,
  bodyArea: {
    flex: 1,
    minWidth: 0,
    padding: "12px 14px",
    border: "none",
    outline: "none",
    resize: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: `${EDITOR_LINE_HEIGHT}px`,
    whiteSpace: "pre",
    overflow: "auto",
  } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 8, width: "100%" } satisfies CSSProperties,
  footerMeta: { flex: 1, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
