import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 16,
    minWidth: 0,
  } satisfies CSSProperties,
  center: { display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 10 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  spacer: { marginLeft: "auto" } satisfies CSSProperties,
  title: { fontSize: 13, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  label: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "0 0 8px",
  } satisfies CSSProperties,
  summary: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.55,
    color: "var(--text-primary)",
    overflowWrap: "anywhere",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", margin: 0, lineHeight: 1.45 } satisfies CSSProperties,
  notice: {
    fontSize: 12.5,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    borderRadius: 6,
    padding: "6px 10px",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  error: {
    fontSize: 12.5,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    borderRadius: 6,
    padding: "6px 10px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  list: { margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  footer: {
    display: "flex",
    gap: 14,
    flexWrap: "wrap",
    fontSize: 12,
    color: "var(--text-muted)",
    borderTop: "1px solid var(--border)",
    paddingTop: 12,
  } satisfies CSSProperties,
  modalBody: { padding: "16px 24px", fontSize: 13.5, lineHeight: 1.5 } satisfies CSSProperties,
  modalFooter: { display: "flex", gap: 8, justifyContent: "flex-end" } satisfies CSSProperties,
} as const;
