import type { CSSProperties } from "react";

const ellipsis = {
  minWidth: 0,
  overflow: "hidden",
  textOverflow: "ellipsis",
  whiteSpace: "nowrap",
} satisfies CSSProperties;

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 16,
    minWidth: 0,
  } satisfies CSSProperties,
  title: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", margin: 0, lineHeight: 1.45 } satisfies CSSProperties,
  center: { display: "flex", flexDirection: "column", gap: 8, alignItems: "flex-start" } satisfies CSSProperties,
  stats: { display: "flex", flexWrap: "wrap", columnGap: 16, rowGap: 6, color: "var(--text-muted)" } satisfies CSSProperties,
  stat: { display: "inline-flex", alignItems: "center", gap: 6, fontSize: 12.5, minWidth: 0 } satisfies CSSProperties,
  statValue: { fontSize: 14, fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  statLabel: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  banner: {
    fontSize: 12.5,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    borderRadius: 6,
    padding: "8px 10px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    alignItems: "flex-start",
  } satisfies CSSProperties,
  bannerTitle: { display: "flex", alignItems: "center", gap: 8, fontWeight: 600 } satisfies CSSProperties,
  list: { margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  symbolCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    minWidth: 0,
  } satisfies CSSProperties,
  symbolHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    width: "100%",
    padding: "9px 12px",
    background: "var(--bg-subtle, transparent)",
    border: 0,
    borderRadius: 8,
    color: "var(--text-muted)",
    cursor: "pointer",
    font: "inherit",
    textAlign: "left",
  } satisfies CSSProperties,
  symbolIcon: { color: "var(--accent)", display: "inline-flex", flexShrink: 0 } satisfies CSSProperties,
  symbolBody: { padding: "0 12px 12px 36px", display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  connector: { color: "var(--text-muted)", display: "inline-flex", flexShrink: 0 } satisfies CSSProperties,
  symbolName: { fontSize: 13, fontWeight: 600, flex: 1, color: "var(--text-primary)", ...ellipsis } satisfies CSSProperties,
  symbolCount: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0, whiteSpace: "nowrap" } satisfies CSSProperties,
  callers: { margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  caller: { display: "flex", alignItems: "center", gap: 8, fontSize: 12, minWidth: 0 } satisfies CSSProperties,
  callerName: { color: "var(--text-muted)", flexShrink: 0, maxWidth: "40%", ...ellipsis } satisfies CSSProperties,
  callerPath: { flex: 1, color: "var(--text-secondary)", textDecoration: "none", ...ellipsis } satisfies CSSProperties,
  other: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  otherLabel: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.4 } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 6 } satisfies CSSProperties,
  endpointChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    maxWidth: "100%",
    padding: "3px 8px",
    borderRadius: 6,
    fontSize: 12,
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
  } satisfies CSSProperties,
  cronChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    maxWidth: "100%",
    padding: "3px 8px",
    borderRadius: 6,
    fontSize: 12,
    color: "var(--warn)",
    background: "var(--warn-bg)",
  } satisfies CSSProperties,
  chipText: { maxWidth: 220, ...ellipsis, display: "inline-block", verticalAlign: "bottom" } satisfies CSSProperties,
} as const;
