import type { CSSProperties } from "react";
import { EDITOR_HEIGHT, EDITOR_LINE_HEIGHT } from "./constants";

const field = {
  width: "100%",
  padding: "10px 12px",
  borderRadius: 7,
  border: "1px solid var(--border-strong)",
  background: "var(--bg-elevated)",
  color: "var(--text-primary)",
  fontSize: 14,
  outline: "none",
} satisfies CSSProperties;

export const s = {
  head: { display: "flex", alignItems: "center", gap: 12, marginBottom: 22 } satisfies CSSProperties,
  title: { fontSize: 17, fontWeight: 650, flex: 1 } satisfies CSSProperties,
  enabled: { display: "flex", alignItems: "center", gap: 10, fontSize: 13, fontWeight: 500, color: "var(--text-secondary)" } satisfies CSSProperties,
  group: { marginBottom: 20 } satisfies CSSProperties,
  labelRow: { display: "flex", alignItems: "center", marginBottom: 8 } satisfies CSSProperties,
  label: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  required: { color: "var(--crit)", marginLeft: 4 } satisfies CSSProperties,
  counter: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  counterOver: { marginLeft: "auto", fontSize: 12, color: "var(--crit)" } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginTop: 8, lineHeight: 1.45 } satisfies CSSProperties,
  error: { fontSize: 12, color: "var(--crit)", marginTop: 6 } satisfies CSSProperties,
  input: { ...field } satisfies CSSProperties,
  textarea: { ...field, resize: "vertical", lineHeight: 1.5 } satisfies CSSProperties,
  select: { ...field, appearance: "none", cursor: "pointer" } satisfies CSSProperties,
  selectWrap: { position: "relative" } satisfies CSSProperties,
  selectIcon: { position: "absolute", right: 12, top: 13, color: "var(--text-muted)", pointerEvents: "none" } satisfies CSSProperties,
  editor: { border: "1px solid var(--border-strong)", borderRadius: 7, background: "var(--code-bg)", overflow: "hidden" } satisfies CSSProperties,
  editorInvalid: { border: "1px solid var(--crit)", borderRadius: 7, background: "var(--code-bg)", overflow: "hidden" } satisfies CSSProperties,
  fileBar: { display: "flex", alignItems: "center", gap: 10, padding: "9px 14px", borderBottom: "1px solid var(--border)", background: "var(--bg-elevated)" } satisfies CSSProperties,
  fileIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  fileName: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  tokens: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  code: { display: "flex", height: EDITOR_HEIGHT } satisfies CSSProperties,
  gutter: {
    width: 44,
    flexShrink: 0,
    overflow: "hidden",
    padding: "12px 10px 12px 0",
    textAlign: "right",
    fontSize: 13,
    lineHeight: `${EDITOR_LINE_HEIGHT}px`,
    color: "var(--text-muted)",
    userSelect: "none",
    borderRight: "1px solid var(--border)",
  } satisfies CSSProperties,
  bodyArea: {
    flex: 1,
    minWidth: 0,
    padding: "12px 14px",
    border: "none",
    outline: "none",
    resize: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: `${EDITOR_LINE_HEIGHT}px`,
    whiteSpace: "pre",
    overflow: "auto",
  } satisfies CSSProperties,
  actions: { display: "flex", alignItems: "center", gap: 10, marginTop: 20 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
} as const;
